site_name: CSS Wuxi MW Exchange Support Doc Site

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
  - Welcome: index.md
  - Exchange: 
    - 'Temporary Authentication Failure': ./exchange/454-temporary-authentication-failure.md