site_name: CSS Wuxi MW Exchange Support Doc Site

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences

nav:
  - Welcome: index.md
  - Exchange: 
    - 'Temporary Authentication Failure': ./exchange/454-temporary-authentication-failure.md
  - Molly: ./hello.md